import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import TheSignal from './TheSignal';

describe('TheSignal', () => {
  it('renders the main heading and description', () => {
    render(<TheSignal />);

    expect(screen.getByText('Podcast')).toBeInTheDocument();
    expect(screen.getByText('// The Signal')).toBeInTheDocument();
    expect(screen.getByText('Audio transmissions from the Federation.')).toBeInTheDocument();
  });

  it('renders the latest transmission details', () => {
    render(<TheSignal />);

    expect(screen.getByText('Episode 42: The Sovereign Web')).toBeInTheDocument();
    expect(screen.getByText('15:42')).toBeInTheDocument();
    const durationElements = screen.getAllByText('45:00');
    expect(durationElements.length).toBeGreaterThan(0);
    expect(durationElements[0]).toBeInTheDocument();
  });

  it('toggles play/pause state when the main button is clicked', () => {
    render(<TheSignal />);

    const playButton = screen.getByRole('button', { name: 'Play Latest Transmission' });
    expect(playButton).toBeInTheDocument();
    expect(screen.getByText('Latest Transmission')).toBeInTheDocument();
    expect(screen.queryByText('Receiving Signal...')).not.toBeInTheDocument();

    // Click to play
    fireEvent.click(playButton);

    // Check if it toggled to pause
    const pauseButton = screen.getByRole('button', { name: 'Pause Latest Transmission' });
    expect(pauseButton).toBeInTheDocument();
    expect(screen.getByText('Receiving Signal...')).toBeInTheDocument();

    // Click to pause
    fireEvent.click(pauseButton);

    // Back to play state
    expect(screen.getByRole('button', { name: 'Play Latest Transmission' })).toBeInTheDocument();
    expect(screen.getByText('Latest Transmission')).toBeInTheDocument();
  });

  it('renders the archives section with episodes', () => {
    render(<TheSignal />);

    expect(screen.getByText('Archives')).toBeInTheDocument();

    // Check for the 3 archived episodes generated by mapping [1, 2, 3]
    expect(screen.getByText('Episode 41: Data is Labor')).toBeInTheDocument();
    expect(screen.getByText('Episode 40: Data is Labor')).toBeInTheDocument();
    expect(screen.getByText('Episode 39: Data is Labor')).toBeInTheDocument();

    // Check for the aired dates
    expect(screen.getByText('Aired: 1 weeks ago')).toBeInTheDocument();
    expect(screen.getByText('Aired: 2 weeks ago')).toBeInTheDocument();
    expect(screen.getByText('Aired: 3 weeks ago')).toBeInTheDocument();
  });
});
